name: voila-gpx-viewer
channels:
  - conda-forge
dependencies:
  - bqplot=0.11.5
  - ipyleaflet=0.11.1
  - ipywidgets=7.5
  - jupyterlab=1.0
  - gpxpy=1.3.5
  - pip
  - voila=0.1.9
  - pip:
    - srtm.py==0.3.4

